FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .

CMD ["npm", "run", "start"]

# command for docker volumes to check changes automatically without new build (for self)
# docker build -t docker16093/createreactapp -f Dockerfile.dev .
# docker run -it -p 3000:3000 -v /app/node_modules -v $(pwd):/app  docker193/createreactapp